channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip
  - pytest
  - cmake
  - ninja
  - libxml2
  - llvmdev=10.0.0
  - clangdev
  - antlr
  - numpy
  - decorator
  - scipy
  - attrs
  - onnx
  - cppzmq
  - spdlog
  - simplejson
  - ffmpeg
  - tokenizers
  - safetensors
  - cxx-compiler
  - cppzmq
  - cxxopts
  - cereal
  - nlohmann_json=3.10.3
  - graphviz
  - boost-cpp
  - pyyaml
  - tqdm
  - transformers=4.32.1
  - huggingface_hub=0.17.3
